LANDGRIFF-244 Excel validation notebook
Vizzuality/landgriffon pull request #234
Opened 2022-02-01 10:12 UTC by AngelArcones

Validation of the input excel by field and by rows

2022-03-01 07:12 UTC, elpamart requested changes
Some minor changes. But in general looks good to me :) I guess at some point we have to consider a validation to check that the data ingested exist in the ddbb apart from the pre-validation, but that is something we can improve in the future.

2022-03-01 07:12 UTC, elpamart commented on data/notebooks/Lab/Excel_validation_logic.ipynb
> +    "                print(f'LOCATION ERROR ON ENTRY {l+1}: address/latitude/longitude not allowed')\n",
I wouldn't say we should provide this as an error but as a warning - the user can provide that information but it's not required/ used for the geocoding or maybe there is a case were the user can provide this information and maybe we can suggest the option of changing the location type?

2022-03-01 07:12 UTC, elpamart commented on data/notebooks/Lab/Excel_validation_logic.ipynb
> +    "                print(f'LOCATION ERROR ON ENTRY {l+1}: address/latitude/longitude not allowed')\n",
same as above

2022-03-01 09:56 UTC, AngelArcones commented
Updated with the changes and comments

2022-03-02 11:34 UTC, elpamart approved these changes

2022-03-02 12:00 UTC, merged