Api/suppliers max name length
Vizzuality/landgriffon pull request #261
Opened 2022-02-22 05:39 UTC by asuramaru1

change max length for supplier name (v3 sourcing data contains bigger names and data ingestion fails)

2022-02-22 09:56 UTC, alexeh approved these changes

2022-02-22 11:05 UTC, tiagojsag requested changes
add a test to cover the change you just made

2022-02-23 12:51 UTC, tiagojsag requested changes

2022-02-23 12:51 UTC, tiagojsag commented on api/test/e2e/suppliers/suppliers-create.spec.ts
> +      .expect(HttpStatus.BAD_REQUEST);
validate that you are getting the expected error message.

2022-02-23 12:51 UTC, tiagojsag commented on api/test/e2e/suppliers/suppliers-update.spec.ts
> +      .expect(HttpStatus.BAD_REQUEST);
same here

2022-02-23 16:15 UTC, tiagojsag approved these changes

2022-02-23 16:16 UTC, merged