Styling inputs, labels to match the designs
Vizzuality/landgriffon pull request #274
Opened 2022-02-25 11:22 UTC by SARodrigues

## Description  

**In this PR:**

TODO

**Notes:**  

TODO

## JIRA  

TODO

## Screenshots

TODO

2022-02-28 09:09 UTC, davidsingal requested changes
![image](https://user-images.githubusercontent.com/674179/155955338-0d4075af-59b2-4091-876a-b5cef060b288.png)

The code looks good, but I think there are missing some styles. The screenshot is for the inline inputs on the intervention form.

2022-02-28 10:42 UTC, SARodrigues commented
> ![image](https://user-images.githubusercontent.com/674179/155955338-0d4075af-59b2-4091-876a-b5cef060b288.png)
> 
> The code looks good, but I think there are missing some styles. The screenshot is for the inline inputs on the intervention form.

Yes, I only added the "default" theme, not an inline one. Will add an "inline" theme shortly.

2022-02-28 14:23 UTC, SARodrigues commented
Updated: 
<img width="713" alt="Screenshot 2022-02-28 at 14 23 40" src="https://user-images.githubusercontent.com/6273795/155999371-6cbbc380-7e33-41d9-b966-01fb9f7346c5.png">

2022-03-01 11:55 UTC, mluena approved these changes

2022-03-01 12:04 UTC, merged