fixing popover position
Vizzuality/landgriffon pull request #302
Opened 2022-03-16 14:04 UTC by AbdoKousara

**fixing the Scenarios items popover position using
headlessui/popover and usePopper**

2022-03-17 14:47 UTC, davidsingal requested changes

2022-03-17 14:47 UTC, davidsingal commented on client/src/containers/scenarios/item/component.tsx
> +                            enter="transition ease-out duration-1000"
duration-100
```suggestion
                            enter="transition ease-out duration-100"
```

2022-03-21 10:30 UTC, mluena requested changes

2022-03-21 10:30 UTC, mluena commented on client/src/containers/scenarios/item/component.tsx
> +const DROPDOWN_ITEM_ACTIVE_CLASSNAME = 'hover:bg-gray-100 hover:text-gray-900';
you could add this hover interaction to previous class and get rid off this one

2022-03-21 10:30 UTC, mluena commented on client/src/containers/scenarios/item/component.tsx
> +
```suggestion
```

2022-03-21 10:30 UTC, mluena commented on client/src/containers/scenarios/item/component.tsx
> +    placement: 'left-start',
```suggestion
    placement: 'right-start',
```

2022-03-21 10:30 UTC, mluena commented on client/src/containers/scenarios/item/component.tsx
> +          offset: [-110, -20],
```suggestion
          offset: [-20, 20],
```

2022-03-25 09:07 UTC, merged