Scenario analysis table
Vizzuality/landgriffon pull request #385
Opened 2022-04-28 13:45 UTC by yulia-bel

PR extends functionality of the Impact Table endpoint:
- Optional property 'scenarioId' has been added to dto (queryParams from client)
- If scenarioId is received, impact data will be additionally filtered to get the impacts belonging to scenario and grouped by the type - Cancelled or Replacing
- based on that data received from DB, for Scenario Impact Table response will additionally have impact after the Intervention and absolute/percentage comparisons

2022-05-19 14:31 UTC, KevSanchez requested changes

2022-05-19 14:31 UTC, KevSanchez commented on api/src/modules/sourcing-records/sourcing-record.repository.ts
> +    }
Already talked about: refactor to subquery

2022-05-30 06:44 UTC, alexeh approved these changes

2022-05-30 08:56 UTC, KevSanchez approved these changes

2022-05-30 13:36 UTC, merged