Client/fix/landgrif 611 editable year range
Vizzuality/landgriffon pull request #388
Opened 2022-05-02 18:42 UTC by JoaquinTrinanes

![image](https://user-images.githubusercontent.com/1385934/166306031-6023e532-d108-48ce-a110-957ab09ce353.png)

2022-05-03 09:30 UTC, davidsingal commented
![Screenshot 2022-05-03 at 11 28 37](https://user-images.githubusercontent.com/674179/166431487-38934ea0-f725-405f-9de4-d3661112619c.png)

There is a bug, I've tried to create the year 2024. The list is not sorted well and it's not selected once is created.

Also, a question: what happens if the user tries to create a not valid year (a string)?

2022-05-04 08:09 UTC, davidsingal requested changes
Now, when I create a new value, it doesn't select it by default

2022-05-19 10:39 UTC, JoaquinTrinanes commented
@davidsingal the component is functional, but styles are pending. All yours! :)

2022-05-23 08:50 UTC, davidsingal approved these changes

2022-05-23 08:50 UTC, merged