Client/fix/landgrif 711 end year ux
Vizzuality/landgriffon pull request #464
Opened 2022-06-10 10:43 UTC by JoaquinTrinanes

### General description

_Please write a description. If the PR is hard to understand, provide a quick explanation of the code._

### Designs

_Link to the related design prototypes (if applicable)_

### Testing instructions

_Provide minimal instructions on how to test this PR._

- Apart from the added feature / bug fix, check overall performance, styling...

## Checklist before merging

- [ ] Branch name / PR includes the related Jira ticket Id.
- [ ] Tests to check core implementation / bug fix added.
- [ ] All checks in Continuous Integration workflow pass.
- [ ] Feature functionally tested by reviewer(s).
- [ ] Code reviewed by reviewer(s).
- [ ] Documentation updated (README, CHANGELOG...) (if required)

2022-06-27 09:41 UTC, JoaquinTrinanes commented
> A green border (focus) is not removable despite you clicking outside. It's only removed if you open and close the dropdown.

This is `react-select`'s default behaviour, I'll try to see if I can tweak it

> Also, ample space is not needed. In the design, the select is adapted to the content width. ![Screenshot 2022-06-27 at 11 16 02](https://user-images.githubusercontent.com/674179/175906206-81ab4172-ba53-4d65-9069-1b3c4aa9d946.png)

With less width there's no space to show the `Type any year`, unless we increase it when it's open&hellip;

> Shouldn't be the blinking cursor at the beginning of the input?? ![Screenshot 2022-06-27 at 11 16 43](https://user-images.githubusercontent.com/674179/175906615-8e2194f4-72c2-4f0a-a7c8-6c072814852e.png)

Yeah it should, `react-select` has a placeholder AND an input, in that order. It doesn't provide a way to change the order, only specific components, but I can try things like reversing the children order (so the input is first) or trying to add the placeholder to the input instead of another specific element.

2022-06-27 09:43 UTC, davidsingal requested changes

2022-06-27 09:43 UTC, davidsingal commented on client/package.json
> +    "@floating-ui/react-dom-interactions": "^0.6.4",
Used fixed versions please

2022-06-27 09:43 UTC, davidsingal commented on client/src/components/select/component.tsx
> +            }
```suggestion
            if (numeric && !/^[0-9]*$/.test(e.currentTarget.value)) return;
```

2022-06-27 09:43 UTC, davidsingal commented on client/package.json
> +    "axios": "^0.27.2",
Same as above, fixed versions

2022-06-27 09:46 UTC, davidsingal commented
![Screenshot 2022-06-27 at 11 45 10](https://user-images.githubusercontent.com/674179/175912364-8ec79c03-dddf-4bde-aff9-a45afb4aa91e.png)
Maybe, react-select put the placeholder over the input.

2022-06-28 07:48 UTC, davidsingal approved these changes

2022-06-28 07:48 UTC, merged