Change impact layer resolution according to zoom value
Vizzuality/landgriffon pull request #900
Opened 2023-02-28 13:19 UTC by barbara-chaves

### General description

This PR changes the resolution of the H3 impact layer to increase based on the map zoom value.

### Testing instructions

TO DO

## Checklist before merging

- [ ] Branch name / PR includes the related Jira ticket Id.
- [ ] Tests to check core implementation / bug fix added.
- [ ] All checks in Continuous Integration workflow pass.
- [ ] Feature functionally tested by reviewer(s).
- [ ] Code reviewed by reviewer(s).
- [ ] Documentation updated (README, CHANGELOG...) (if required)

2023-03-02 09:17 UTC, davidsingal requested changes
It looks good to me, I've only left a comment about a package that could be duplicated

2023-03-02 09:17 UTC, davidsingal commented on client/package.json
> +    "use-debounce": "^9.0.3",
if I'm not wrong rooks package already includes useDebounce, could you check it?

2023-03-02 09:47 UTC, davidsingal approved these changes

2023-03-03 11:26 UTC, davidsingal commented
could you check with Andrés if you will have some conflicts with the layer manager integration here? #903

2023-03-06 10:30 UTC, davidsingal commented
Please use the origin filter instead of location type @barbara-chaves

2023-03-07 09:29 UTC, davidsingal requested changes

2023-03-07 09:29 UTC, davidsingal commented on client/src/components/map/component.tsx
> +
I think this is the reason why moving the map with the mouse it very slow

2023-03-07 17:18 UTC, andresgnlez approved these changes

2023-03-08 08:50 UTC, davidsingal approved these changes

2023-05-19 06:59 UTC, closed without merging